<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT *
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [4]:
%%sql

SELECT *
FROM product
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [5]:
%%sql

SELECT
  p.categoryname,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_net_revenue_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS min_net_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_net_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_net_revenue_2023,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS min_net_revenue_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_net_revenue_2023
FROM sales s
LEFT JOIN product p
  ON p.productkey = s.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_revenue_2022,min_net_revenue_2022,max_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2023,max_net_revenue_2023
0,Audio,392.30,9.31,3473.36,425.38,10.85,2730.87
1,Cameras and camcorders,1210.02,6.74,15008.39,1210.96,5.98,13572.00
2,Cell phones,722.20,2.53,7692.37,623.28,2.28,8912.22
3,Computers,1565.62,0.83,38082.66,1292.39,0.75,27611.60
4,Games and Toys,81.29,2.83,5202.01,80.83,3.49,3357.30
5,Home Appliances,1755.36,4.04,31654.55,1886.55,4.54,32915.59
6,"Music, Movies and Audio Books",386.61,7.29,5415.19,334.58,6.91,3804.91
7,TV and Video,1535.61,41.30,30259.41,1687.90,42.30,27503.12

In [6]:
%%sql

SELECT
  PERCENTILE_CONT(.50) WITHIN GROUP (ORDER BY netprice) AS median_price
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [7]:
%%sql

SELECT
  AVG(netprice)
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

     avg
0 324.30

In [8]:
%%sql

SELECT
  p.categoryname,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE
    WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate)
  END)) AS y2022_median_sales,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE
    WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate)
  END)) AS y2023_median_sales
FROM
  sales s
  LEFT JOIN product p ON p.productkey = s.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79

In [9]:
%%sql

SELECT
  orderdate,
  quantity,
  netprice,
  CASE
    WHEN quantity >= 2 AND netprice >= 50 THEN 'High Value Order'
    ELSE 'Standard Order'
  END AS order_type
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice        order_type
0  2015-01-01         1     98.97    Standard Order
1  2015-01-01         1    659.78    Standard Order
2  2015-01-01         2     54.38  High Value Order
3  2015-01-01         4    286.69  High Value Order
4  2015-01-01         7    135.75  High Value Order
5  2015-01-01         3    434.30  High Value Order
6  2015-01-01         1     58.73    Standard Order
7  2015-01-01         3     74.99  High Value Order
8  2015-01-01         2    113.57  High Value Order
9  2015-01-01         1    499.45    Standard Order

In [10]:
%%sql

SELECT
  orderdate,
  quantity,
  netprice,
  CASE
    WHEN quantity >= 2 AND netprice >= 100 THEN 'Mulitple High Value Items'
    WHEN netprice >= 100 THEN 'Single High Value Item'
    WHEN quantity >=2 THEN 'Multiple Standard Items'
    ELSE 'Single Standard Item'
  END AS categorize
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 categorize
0  2015-01-01         1     98.97       Single Standard Item
1  2015-01-01         1    659.78     Single High Value Item
2  2015-01-01         2     54.38    Multiple Standard Items
3  2015-01-01         4    286.69  Mulitple High Value Items
4  2015-01-01         7    135.75  Mulitple High Value Items
5  2015-01-01         3    434.30  Mulitple High Value Items
6  2015-01-01         1     58.73       Single Standard Item
7  2015-01-01         3     74.99    Multiple Standard Items
8  2015-01-01         2    113.57  Mulitple High Value Items
9  2015-01-01         1    499.45     Single High Value Item

In [11]:
%%sql

SELECT
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
FROM
  sales s
WHERE
  orderdate BETWEEN '2022-01-01' AND '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [12]:
%%sql

WITH median_value AS (
    SELECT
      PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
    FROM
      sales s
    WHERE
      orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
          AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
      THEN (s.quantity * s.netprice * s.exchangerate)
  END) AS low_net_revenue_2022,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
          AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
      THEN (s.quantity * s.netprice * s.exchangerate)
  END) AS high_net_revenue_2022,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
          AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
      THEN (s.quantity * s.netprice * s.exchangerate)
  END) AS low_net_revenue_2023,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
          AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
      THEN (s.quantity * s.netprice * s.exchangerate)
  END) AS high_net_revenue_2023

FROM
  sales s
  LEFT JOIN product p ON p.productkey = s.productkey,
  median_value mv
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

In [13]:
%%sql

WITH percentile AS (
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS revenue_25th_percentile,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS revenue_75th_percentile
  FROM
    sales s
  WHERE
    orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)
SELECT
    p.categoryname AS category,
    CASE
      WHEN (s.quantity * s.netprice * s.exchangerate) <= pctl.revenue_25th_percentile THEN '3 - LOW'
      WHEN (s.quantity * s.netprice * s.exchangerate) >= pctl.revenue_75th_percentile THEN '1 - HIGH'
      ELSE '2 - MEDIUM'
    END AS revenue_tier,
    SUM(s.quantity * s.netprice * s.exchangerate) AS total_revenue
FROM
    sales s
    LEFT JOIN product p ON p.productkey = s.productkey,
    percentile pctl
GROUP BY
    p.categoryname,
    revenue_tier
ORDER BY
    p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio     1 - HIGH     1213265.71
1                           Audio   2 - MEDIUM     3832415.38
2                           Audio      3 - LOW      267217.01
3         Cameras and camcorders      1 - HIGH    15050781.63
4         Cameras and camcorders    2 - MEDIUM     3388546.10
5         Cameras and camcorders       3 - LOW       81032.92
6                     Cell phones     1 - HIGH    21874993.15
7                     Cell phones   2 - MEDIUM    10338963.22
8                     Cell phones      3 - LOW      410309.35
9                       Computers     1 - HIGH    79607760.89
10                      Computers   2 - MEDIUM    10808054.11
11                      Computers      3 - LOW      203207.06
12                 Games and Toys     1 - HIGH      133749.09
13                 Games and Toys   2 - MEDIUM     1001381.91
14                 Games and Toys      3 - LOW      533443.13
15                Home Appliances     1 - HIGH    22383475.30
16                Home Appliances   2 - MEDIUM     4118724.64
17                Home Appliances      3 - LOW      105045.60
18  Music, Movies and Audio Books     1 - HIGH     3844996.29
19  Music, Movies and Audio Books   2 - MEDIUM     6100817.99
20  Music, Movies and Audio Books      3 - LOW      642496.71
21                   TV and Video     1 - HIGH    16632856.33
22                   TV and Video   2 - MEDIUM     3766783.30
23                   TV and Video      3 - LOW       67221.76

In [14]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS order_month,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM sales s
GROUP BY
    order_month
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_month  net_revenue  total_unique_customers
0     2015-01    384092.66                     200
1     2015-02    706374.12                     291
2     2015-03    332961.59                     139
3     2015-04    160767.00                      78
4     2015-05    548632.63                     236
5     2015-06    748563.97                     238
6     2015-07    635376.13                     227
7     2015-08    718538.62                     235
8     2015-09    696805.68                     277
9     2015-10    824891.22                     304

In [15]:
%%sql

SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(MONTH FROM orderdate) AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
GROUP BY
    order_year,
    order_month
ORDER BY
    order_year,
    order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue
0         2015           1    384092.66
1         2015           2    706374.12
2         2015           3    332961.59
3         2015           4    160767.00
4         2015           5    548632.63
..         ...         ...          ...
107       2023          12   2928550.93
108       2024           1   2677498.55
109       2024           2   3542322.55
110       2024           3   1692854.89
111       2024           4    483851.39

[112 rows x 3 columns]

In [16]:
%%sql

SELECT
  CURRENT_DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2026-03-11

In [17]:
%%sql

SELECT
  NOW()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

                               now
0 2026-03-11 19:08:00.694735+00:00

In [18]:
%%sql

SELECT
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN product p ON p.productkey = s.productkey
WHERE
  EXTRACT(YEAR FROM orderdate) >= EXTRACT(YEAR FROM CURRENT_DATE) - 5
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

       orderdate                   categoryname  net_revenue
0     2021-01-01                          Audio      1206.67
1     2021-01-01        Cameras and camcorders       2228.75
2     2021-01-01                    Cell phones     10582.00
3     2021-01-01                      Computers     12718.95
4     2021-01-01                 Games and Toys       235.53
...          ...                            ...          ...
8952  2024-04-20                      Computers     58353.68
8953  2024-04-20                 Games and Toys      1744.30
8954  2024-04-20                Home Appliances      1562.04
8955  2024-04-20  Music, Movies and Audio Books      4949.43
8956  2024-04-20                   TV and Video      9841.91

[8957 rows x 3 columns]

In [19]:
%%sql

SELECT
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN product p ON p.productkey = s.productkey
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8517 rows affected.

       orderdate                   categoryname  net_revenue
0     2021-03-11                          Audio      2292.66
1     2021-03-11                    Cell phones     12854.69
2     2021-03-11                      Computers     16622.07
3     2021-03-11                 Games and Toys       313.08
4     2021-03-11                Home Appliances       622.16
...          ...                            ...          ...
8512  2024-04-20                      Computers     58353.68
8513  2024-04-20                 Games and Toys      1744.30
8514  2024-04-20                Home Appliances      1562.04
8515  2024-04-20  Music, Movies and Audio Books      4949.43
8516  2024-04-20                   TV and Video      9841.91

[8517 rows x 3 columns]

In [19]:
%%sql

SELECT

In [32]:
%%sql

SELECT
  DATE_PART('year', orderdate) AS order_year,
  ROUND(AVG(EXTRACT(DAYS FROM AGE(deliverydate, orderdate))), 2) AS avg_processing_time,
  CAST(SUM(quantity * netprice * exchangerate) AS INT) AS net_revenue
FROM
  sales
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY
  order_year
ORDER BY
  order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

   order_year avg_processing_time  net_revenue
0     2021.00                1.39     19301186
1     2022.00                1.62     44864557
2     2023.00                1.75     33108566
3     2024.00                1.67      8396527

In [34]:
%%sql

SELECT
  customerkey,
  orderkey,
  linenumber,
  (quantity * netprice * exchangerate) AS net_revenue,
  AVG(quantity * netprice * exchangerate) OVER() AS avg_net_revenue_all_orders,
  AVG(quantity * netprice * exchangerate) OVER(PARTITION BY customerkey) AS avg_net_revenue_this_customer
FROM sales
ORDER BY customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderkey,linenumber,net_revenue,avg_net_revenue_all_orders,avg_net_revenue_this_customer
0,15,2259001,0,2217.41,1032.69,2217.41
1,180,3162018,0,71.36,1032.69,836.74
2,180,3162018,1,1913.55,1032.69,836.74
3,180,1305016,0,525.31,1032.69,836.74
4,185,1613010,0,1395.52,1032.69,1395.52
5,243,505008,0,287.67,1032.69,287.67
6,387,3242015,2,180.35,1032.69,517.32
7,387,3242015,3,446.44,1032.69,517.32
8,387,3242015,1,362.44,1032.69,517.32
9,387,3242015,0,30.51,1032.69,517.32

In [43]:
%%sql

SELECT
  customerkey AS customer,
  orderdate,
  (quantity * netprice * exchangerate) AS net_revenue,
  ROW_NUMBER() OVER(
    PARTITION BY customerkey
    ORDER BY quantity * netprice * exchangerate DESC
  ) AS order_rank,
  SUM(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS customer_running_total,
  SUM(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
  ) AS customer_net_revenue,
  (quantity * netprice * exchangerate) / SUM(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
  ) * 100 AS pct_custoemr_revenue
FROM sales
ORDER BY customerkey, orderdate
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customer,orderdate,net_revenue,order_rank,customer_running_total,customer_net_revenue,pct_custoemr_revenue
0,15,2021-03-08,2217.41,1,2217.41,2217.41,100.00
1,180,2018-07-28,525.31,2,525.31,2510.22,20.93
2,180,2023-08-28,1913.55,1,2510.22,2510.22,76.23
3,180,2023-08-28,71.36,3,2510.22,2510.22,2.84
4,185,2019-06-01,1395.52,1,1395.52,1395.52,100.00
5,243,2016-05-19,287.67,1,287.67,287.67,100.00
6,387,2018-12-21,619.77,3,2370.54,4655.84,13.31
7,387,2018-12-21,1608.10,1,2370.54,4655.84,34.54
8,387,2018-12-21,97.05,7,2370.54,4655.84,2.08
9,387,2018-12-21,45.62,8,2370.54,4655.84,0.98

In [51]:
%%sql

SELECT
  orderdate,
  orderkey * 10 + linenumber AS order_line_number,
  (quantity * netprice * exchangerate) AS net_revenue,
  SUM(quantity * netprice * exchangerate) OVER(
    PARTITION BY orderdate
  ) AS daily_net_revenue,
  (quantity * netprice * exchangerate) * 100 / SUM(quantity * netprice * exchangerate) OVER(
    PARTITION BY orderdate
  ) AS pct_daily_revenue
FROM
  sales
ORDER BY
  orderdate,
  pct_daily_revenue DESC
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
5,2015-01-01,10021,950.25,11640.80,8.16
6,2015-01-01,10041,578.52,11640.80,4.97
7,2015-01-01,10081,574.05,11640.80,4.93
8,2015-01-01,10001,423.28,11640.80,3.64
9,2015-01-01,10040,263.11,11640.80,2.26

In [53]:
%%sql
SELECT *
FROM(
  SELECT
    orderdate,
    orderkey * 10 + linenumber AS order_line_number,
    (quantity * netprice * exchangerate) AS net_revenue,
    SUM(quantity * netprice * exchangerate) OVER(
      PARTITION BY orderdate
    ) AS daily_net_revenue
  FROM
    sales
) AS revenue_by_day

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  order_line_number  net_revenue  daily_net_revenue
0       2015-01-01              10000        63.49           11640.80
1       2015-01-01              10001       423.28           11640.80
2       2015-01-01              10010       108.75           11640.80
3       2015-01-01              10020      1146.75           11640.80
4       2015-01-01              10021       950.25           11640.80
...            ...                ...          ...                ...
199868  2024-04-20           33980341       914.61           96879.43
199869  2024-04-20           33980342       150.18           96879.43
199870  2024-04-20           33980350       147.78           96879.43
199871  2024-04-20           33980351      2019.62           96879.43
199872  2024-04-20           33980352        56.83           96879.43

[199873 rows x 4 columns]

In [68]:
%%sql

WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (
    PARTITION BY customerkey)
  ) AS cohort_year
  FROM
    sales
)
SELECT
  y.cohort_year,
  EXTRACT(YEAR FROM s.orderdate) AS purchase_year,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM
  sales s
LEFT JOIN
  yearly_cohort y
    ON s.customerkey = y.customerkey
GROUP BY
  y.cohort_year,
  purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  net_revenue
0         2015          2015   7370979.48
1         2015          2016    392623.48
2         2015          2017    479841.31
3         2015          2018   1069850.87
4         2015          2019   1235991.48
5         2015          2020    386489.60
6         2015          2021    872845.99
7         2015          2022   1569787.72
8         2015          2023   1157633.91
9         2015          2024    356186.62
10        2016          2016   9990990.20
11        2016          2017    497028.11
12        2016          2018   1074607.29
13        2016          2019   1565400.72
14        2016          2020    474087.09
15        2016          2021    964417.85
16        2016          2022   2164681.10
17        2016          2023   1265242.63
18        2016          2024    364066.76
19        2017          2017  12244469.63
20        2017          2018   1407065.13
21        2017          2019   1764716.90
22        2017          2020    625928.03
23        2017          2021   1329858.72
24        2017          2022   2428882.80
25        2017          2023   1714010.18
26        2017          2024    464802.56
27        2018          2018  21115924.55
28        2018          2019   3229188.22
29        2018          2020   1171126.65
30        2018          2021   2201262.39
31        2018          2022   4534295.81
32        2018          2023   3271753.92
33        2018          2024    936833.89
34        2019          2019  24022798.65
35        2019          2020   1295044.99
36        2019          2021   2337594.77
37        2019          2022   4848980.74
38        2019          2023   3440099.20
39        2019          2024    751725.53
40        2020          2020   7265759.44
41        2020          2021   1016399.07
42        2020          2022   1891708.40
43        2020          2023   1435051.04
44        2020          2024    312983.02
45        2021          2021  12635597.87
46        2021          2022   3014082.50
47        2021          2023   2242369.63
48        2021          2024    495686.18
49        2022          2022  24412138.13
50        2022          2023   4237220.04
51        2022          2024   1223450.12
52        2023          2023  14345184.96
53        2023          2024    634143.37
54        2024          2024   2856649.33

In [72]:
%%sql

WITH customer_orders AS(
  SELECT
    customerkey,
    (quantity * netprice * exchangerate) AS order_value,
    COUNT(*) OVER(PARTITION BY customerkey) AS total_orders
  FROM
    sales
)
SELECT
  customerkey,
  total_orders,
  AVG(order_value) AS net_revenue
FROM customer_orders
GROUP BY
  customerkey,
  total_orders

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey  total_orders  net_revenue
0               15             1      2217.41
1              180             3       836.74
2              185             1      1395.52
3              243             1       287.67
4              387             9       517.32
...            ...           ...          ...
49482      2099619             8       838.74
49483      2099656            13       800.36
49484      2099697             3        12.73
49485      2099711             2      3004.34
49486      2099743             3       356.03

[49487 rows x 3 columns]