<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT *
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [5]:
%%sql

SELECT *
FROM product
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [7]:
%%sql

SELECT
  p.categoryname,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_net_revenue_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS min_net_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_net_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_net_revenue_2023,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS min_net_revenue_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_net_revenue_2023
FROM sales s
LEFT JOIN product p
  ON p.productkey = s.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_revenue_2022,min_net_revenue_2022,max_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2023,max_net_revenue_2023
0,Audio,392.30,9.31,3473.36,425.38,10.85,2730.87
1,Cameras and camcorders,1210.02,6.74,15008.39,1210.96,5.98,13572.00
2,Cell phones,722.20,2.53,7692.37,623.28,2.28,8912.22
3,Computers,1565.62,0.83,38082.66,1292.39,0.75,27611.60
4,Games and Toys,81.29,2.83,5202.01,80.83,3.49,3357.30
5,Home Appliances,1755.36,4.04,31654.55,1886.55,4.54,32915.59
6,"Music, Movies and Audio Books",386.61,7.29,5415.19,334.58,6.91,3804.91
7,TV and Video,1535.61,41.30,30259.41,1687.90,42.30,27503.12

In [8]:
%%sql

SELECT
  PERCENTILE_CONT(.50) WITHIN GROUP (ORDER BY netprice) AS median_price
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [9]:
%%sql

SELECT
  AVG(netprice)
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

     avg
0 324.30

In [12]:
%%sql

SELECT
  p.categoryname,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE
    WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate)
  END)) AS y2022_median_sales,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE
    WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate)
  END)) AS y2023_median_sales
FROM
  sales s
  LEFT JOIN product p ON p.productkey = s.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79

In [16]:
%%sql

SELECT
  orderdate,
  quantity,
  netprice,
  CASE
    WHEN quantity >= 2 AND netprice >= 50 THEN 'High Value Order'
    ELSE 'Standard Order'
  END AS order_type
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice        order_type
0  2015-01-01         1     98.97    Standard Order
1  2015-01-01         1    659.78    Standard Order
2  2015-01-01         2     54.38  High Value Order
3  2015-01-01         4    286.69  High Value Order
4  2015-01-01         7    135.75  High Value Order
5  2015-01-01         3    434.30  High Value Order
6  2015-01-01         1     58.73    Standard Order
7  2015-01-01         3     74.99  High Value Order
8  2015-01-01         2    113.57  High Value Order
9  2015-01-01         1    499.45    Standard Order

In [19]:
%%sql

SELECT
  orderdate,
  quantity,
  netprice,
  CASE
    WHEN quantity >= 2 AND netprice >= 100 THEN 'Mulitple High Value Items'
    WHEN netprice >= 100 THEN 'Single High Value Item'
    WHEN quantity >=2 THEN 'Multiple Standard Items'
    ELSE 'Single Standard Item'
  END AS categorize
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 categorize
0  2015-01-01         1     98.97       Single Standard Item
1  2015-01-01         1    659.78     Single High Value Item
2  2015-01-01         2     54.38    Multiple Standard Items
3  2015-01-01         4    286.69  Mulitple High Value Items
4  2015-01-01         7    135.75  Mulitple High Value Items
5  2015-01-01         3    434.30  Mulitple High Value Items
6  2015-01-01         1     58.73       Single Standard Item
7  2015-01-01         3     74.99    Multiple Standard Items
8  2015-01-01         2    113.57  Mulitple High Value Items
9  2015-01-01         1    499.45     Single High Value Item

In [23]:
%%sql

SELECT
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
FROM
  sales s
WHERE
  orderdate BETWEEN '2022-01-01' AND '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [34]:
%%sql

WITH median_value AS (
    SELECT
      PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
    FROM
      sales s
    WHERE
      orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
          AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
      THEN (s.quantity * s.netprice * s.exchangerate)
  END) AS low_net_revenue_2022,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
          AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
      THEN (s.quantity * s.netprice * s.exchangerate)
  END) AS high_net_revenue_2022,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
          AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
      THEN (s.quantity * s.netprice * s.exchangerate)
  END) AS low_net_revenue_2023,

  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
          AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
      THEN (s.quantity * s.netprice * s.exchangerate)
  END) AS high_net_revenue_2023

FROM
  sales s
  LEFT JOIN product p ON p.productkey = s.productkey,
  median_value mv
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

In [42]:
%%sql

WITH percentile AS (
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS revenue_25th_percentile,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS revenue_75th_percentile
  FROM
    sales s
  WHERE
    orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)
SELECT
    p.categoryname AS category,
    CASE
      WHEN (s.quantity * s.netprice * s.exchangerate) <= pctl.revenue_25th_percentile THEN '3 - LOW'
      WHEN (s.quantity * s.netprice * s.exchangerate) >= pctl.revenue_75th_percentile THEN '1 - HIGH'
      ELSE '2 - MEDIUM'
    END AS revenue_tier,
    SUM(s.quantity * s.netprice * s.exchangerate) AS total_revenue
FROM
    sales s
    LEFT JOIN product p ON p.productkey = s.productkey,
    percentile pctl
GROUP BY
    p.categoryname,
    revenue_tier
ORDER BY
    p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio     1 - HIGH     1213265.71
1                           Audio   2 - MEDIUM     3832415.38
2                           Audio      3 - LOW      267217.01
3         Cameras and camcorders      1 - HIGH    15050781.63
4         Cameras and camcorders    2 - MEDIUM     3388546.10
5         Cameras and camcorders       3 - LOW       81032.92
6                     Cell phones     1 - HIGH    21874993.15
7                     Cell phones   2 - MEDIUM    10338963.22
8                     Cell phones      3 - LOW      410309.35
9                       Computers     1 - HIGH    79607760.89
10                      Computers   2 - MEDIUM    10808054.11
11                      Computers      3 - LOW      203207.06
12                 Games and Toys     1 - HIGH      133749.09
13                 Games and Toys   2 - MEDIUM     1001381.91
14                 Games and Toys      3 - LOW      533443.13
15                Home Appliances     1 - HIGH    22383475.30
16                Home Appliances   2 - MEDIUM     4118724.64
17                Home Appliances      3 - LOW      105045.60
18  Music, Movies and Audio Books     1 - HIGH     3844996.29
19  Music, Movies and Audio Books   2 - MEDIUM     6100817.99
20  Music, Movies and Audio Books      3 - LOW      642496.71
21                   TV and Video     1 - HIGH    16632856.33
22                   TV and Video   2 - MEDIUM     3766783.30
23                   TV and Video      3 - LOW       67221.76

In [52]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS order_month,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM sales s
GROUP BY
    order_month
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_month  net_revenue  total_unique_customers
0     2015-01    384092.66                     200
1     2015-02    706374.12                     291
2     2015-03    332961.59                     139
3     2015-04    160767.00                      78
4     2015-05    548632.63                     236
5     2015-06    748563.97                     238
6     2015-07    635376.13                     227
7     2015-08    718538.62                     235
8     2015-09    696805.68                     277
9     2015-10    824891.22                     304

In [56]:
%%sql

SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(MONTH FROM orderdate) AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
GROUP BY
    order_year,
    order_month
ORDER BY
    order_year,
    order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue
0         2015           1    384092.66
1         2015           2    706374.12
2         2015           3    332961.59
3         2015           4    160767.00
4         2015           5    548632.63
..         ...         ...          ...
107       2023          12   2928550.93
108       2024           1   2677498.55
109       2024           2   3542322.55
110       2024           3   1692854.89
111       2024           4    483851.39

[112 rows x 3 columns]

In [57]:
%%sql

SELECT
  CURRENT_DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2026-03-09

In [58]:
%%sql

SELECT
  NOW()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

                               now
0 2026-03-09 13:45:58.284139+00:00

In [72]:
%%sql

SELECT
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN product p ON p.productkey = s.productkey
WHERE
  EXTRACT(YEAR FROM orderdate) >= EXTRACT(YEAR FROM CURRENT_DATE) - 5
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

       orderdate                   categoryname  net_revenue
0     2021-01-01                          Audio      1206.67
1     2021-01-01        Cameras and camcorders       2228.75
2     2021-01-01                    Cell phones     10582.00
3     2021-01-01                      Computers     12718.95
4     2021-01-01                 Games and Toys       235.53
...          ...                            ...          ...
8952  2024-04-20                      Computers     58353.68
8953  2024-04-20                 Games and Toys      1744.30
8954  2024-04-20                Home Appliances      1562.04
8955  2024-04-20  Music, Movies and Audio Books      4949.43
8956  2024-04-20                   TV and Video      9841.91

[8957 rows x 3 columns]

In [73]:
%%sql

SELECT
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN product p ON p.productkey = s.productkey
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8533 rows affected.

       orderdate                   categoryname  net_revenue
0     2021-03-09                          Audio      1662.67
1     2021-03-09        Cameras and camcorders       6422.56
2     2021-03-09                    Cell phones      5943.81
3     2021-03-09                      Computers     17087.65
4     2021-03-09                 Games and Toys       224.89
...          ...                            ...          ...
8528  2024-04-20                      Computers     58353.68
8529  2024-04-20                 Games and Toys      1744.30
8530  2024-04-20                Home Appliances      1562.04
8531  2024-04-20  Music, Movies and Audio Books      4949.43
8532  2024-04-20                   TV and Video      9841.91

[8533 rows x 3 columns]